name:                ui
version:             0.1.0.0
github:              "githubuser/ui"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/ui#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- unix
- xmonad
- xmonad-contrib
- network
- regex-posix
- yi-core
- yi-frontend-pango
- yi-misc-modes
- yi-mode-haskell
- yi-mode-javascript
- yi-language
- yi-fuzzy-open
- yi-keymap-vim

library:
  source-dirs: src

executables:
  ui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ui
